# Generated by Django 4.2.7 on 2025-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_servicerequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Token for Push Notifications'),
        ),
    ]
